local M = {
    active_plugin = 1,
    size_stabilize = true,
    cursorcolumn = false,
    cursorline = false,
    signcolumn = false,
    signcolumn_value = "yes",
    colorcolumn = false,
    colorcolumn_value = "80",
    number = false,
    relativenumber = true,
    winhighlight = true,
    blacklist_ft = {
        "ctrlspace",
        "packer",
        "undotree",
        "diff",
        "Outline",
        "NvimTree",
        "LvimHelper",
        "floaterm",
        "toggleterm",
        "Trouble",
        "dashboard",
        "vista",
        "spectre_panel",
        "DiffviewFiles",
        "flutterToolsOutline",
        "log",
        "qf",
        "dapui_scopes",
        "dapui_breakpoints",
        "dapui_stacks",
        "dapui_watches",
        "calendar",
    },
    blacklist_bt = {
        "nofile",
        "quickfix",
        "help",
        "terminal",
        "directory",
        "scratch",
        "unlisted",
    },
}

return M
